sudo: required
language: python

python:
  - "3.5"
  - "3.6"

services:
  - docker

before_install:
  - docker-compose up -d

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - pytest -v --tb=no

deploy:
  provider: pypi
  user:
    secure: pnh1tw8Zil+njk4t0Ri1WbveFJm/KdCxDFf0ViZ6jPZq5zs81cb52oRnEGTlxxODzsmu2M+Y4Vs5mjg0jPPv8ntdMv2t/Z5ZVR84O8r+tmyHxZO+/Kqs4Y3k0PTFquJXFI09jHrrLUs0jsPI4tH6TgfFELk1K6xqhNlGsAs/NxI15m1Z/mq7GUrsOvEwiu9rcmAWewgIAu31oBIZH6qjAzaKzSB/Su+InhnkTyX0xrN9UlrNbhq5/bCVFMCZF63EigfXybMzgbOuZLH20lz20VGyRCjz1zuojCQHngS/aPRuARyZWx1e7YkNpBNpdFo8ttOfGs0jHQ5PJsf+H5qi/oH6X8E6UHf1Qmi14nEH4Hs/T4zAGrSA7PIkrx2zb7fmIPDbrfkqRp0IvSoHvD79lN0ne28PanX4mjwol21uWXMREcQIXShfo/6mF/LLF9SPUtO4lAAzhvp0dPzRWkYCRjkAVQnf9QOiMJRaz0f8hwy0nxlkGNGjSf44zkctpbFse9w74MH78kMgzumn8B5FKS2ZSDR31knsKjdVOWcS0Y6M1L0oKYjG4laCBk/4ouWZvXiNgJKlzO2jzAK61Qknq/NsIlZV1FeLtHons6fHiQlY3694qd9xs4fZO2Z8UeyU2cwPB0ha8HUpdZimHeb9Hj4REGUfrgLTgiNYhVlnUIM=
  password:
    secure: a0Y4MEdCTMdyo6SBlpJP2BS2mZiLjIhsTuNZFWeCJKPEJ12L6IqwGCxSKUFGptkP0j9Jp9AR98XAyFTpUsgrp8DjAK3Ex/VVQIzUyQ7ZISkVJE8MKFk5v8x7ESNFJJRhYzVEEB84zIiOcJXzAHSKaAFnOqY0t6PxJOzk2ElvSiw89tPneLDjCTNPs3CrEaixkaDTU5naZclsCKIt7p5UCjOOcmny9uJUKHum5zEXFVCmJTNPiv1o6L7VvaHpG+G8B2eTTX3dBIzvCJ6af1BlUwgE6/Fr9cA1wt5o6AXd3e+a+oCIa/gaADeCWUQtfkkSClc0IT9TFLR0LosYwJttzCZllt/fVDDrRjDjgHOsrQApltYP3yMYBk5SJ/Rve8KpBqG4mYJMiGfYElMSavaDSLeSN8h4hMHom7YW+HFR3F7YRSDPlh3ZMKoeDclObc6MzimTOQCqbPYx4zGFAzBQUeRrXkaVwvUw9eNYMiMZOHyEzKrVSpBDSY78pE7MnIMMirWWBQLog79WLplJqIChFC+T/QL7uvjZniQtHzRobt3J6RO84pjtKr9woQUHJGgwGdyerbVj+C8jkE9Fbe1MjqlQZ2HiBScSTUUy9rDGgX9mzNxm4Kh4mHLufrhx1yP6jtOpC7S8PFt2WxaJpwDGaU3aF6kgqm3wFm/JKU6xG94=
  on:
    tags: true
