sudo: required
language: python

python:
  - "3.5"
  - "3.6"


services:
  - docker

before_install:
  - docker-compose up -d

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - pytest
