version: '3'
services:
  mongo:
    image: "mongo:latest"
    ports:
     - "27019:27017"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"